package com.example.proyectoNotas_main.ui.theme

import androidx.compose.ui.graphics.Color
val md_theme_light_primary = Color(0xFF4C2BE4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF4C2BE4)
val md_theme_light_onPrimaryContainer = Color(0xFFFFFFFF)
val md_theme_light_secondary = Color(0xFF000000)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD4E8D1)
val md_theme_light_onSecondaryContainer = Color(0xFF030303)
val md_theme_light_tertiary = Color(0xFFFF0064)
val md_theme_light_onTertiary = Color(0xFF000000)
val md_theme_light_tertiaryContainer = Color(0xFF000000)
val md_theme_light_onTertiaryContainer = Color(0xFF00DCFF)
val md_theme_light_error = Color(0xFFFF0000)
val md_theme_light_errorContainer = Color(0xFFFF1900)
val md_theme_light_onError = Color(0xFFFF0000)
val md_theme_light_onErrorContainer = Color(0xFFB60409)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFCFDF7)
val md_theme_light_onSurface = Color(0xFF000000)
val md_theme_light_surfaceVariant = Color(0xFFC4C7C2)
val md_theme_light_onSurfaceVariant = Color(0xFF000000)
val md_theme_light_outline = Color(0xFF000000)
val md_theme_light_inverseOnSurface = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFFFFFFFF)
val md_theme_light_inversePrimary = Color(0xFF8B0EE4)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF33006E)
val md_theme_light_outlineVariant = Color(0xFF000000)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFAD62F8)
val md_theme_dark_onPrimary = Color(0xFF000000)
val md_theme_dark_primaryContainer = Color(0xFFFFFFFF)
val md_theme_dark_onPrimaryContainer = Color(0xFF000000)
val md_theme_dark_secondary = Color(0xFFB8CCB5)
val md_theme_dark_onSecondary = Color(0xFF243425)
val md_theme_dark_secondaryContainer = Color(0xFF3A4B3A)
val md_theme_dark_onSecondaryContainer = Color(0xFFD4E8D1)
val md_theme_dark_tertiary = Color(0xFFA1CED6)
val md_theme_dark_onTertiary = Color(0xFF00363D)
val md_theme_dark_tertiaryContainer = Color(0xFF1F4D54)
val md_theme_dark_onTertiaryContainer = Color(0xFFBDEAF3)
val md_theme_dark_error = Color(0xFFFF1B00)
val md_theme_dark_errorContainer = Color(0xFFFF0011)
val md_theme_dark_onError = Color(0xFFFF000C)
val md_theme_dark_onErrorContainer = Color(0xFFFF1900)
val md_theme_dark_background = Color(0xFF1A1C19)
val md_theme_dark_onBackground = Color(0xFFE2E3DD)
val md_theme_dark_surface = Color(0xFF1A1C19)
val md_theme_dark_onSurface = Color(0xFFE2E3DD)
val md_theme_dark_surfaceVariant = Color(0xFF424940)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C9BE)
val md_theme_dark_outline = Color(0xFF8B9389)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C19)
val md_theme_dark_inverseSurface = Color(0xFFE2E3DD)
val md_theme_dark_inversePrimary = Color(0xFF818A84)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF3E494B)
val md_theme_dark_outlineVariant = Color(0xFF424940)
val md_theme_dark_scrim = Color(0xFFFFFFFF)


val seed = Color(0xFF3F51B5)